name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Authenticate Docker with GCR
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | docker login -u _json_key --password-stdin https://gcr.io

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/my-knowledge-site-web:latest ./web

    - name: Push Docker image to GCR
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT }}/my-knowledge-site-web:latest

    - name: Set up Kustomize
      run: |
        sudo apt-get install -y kustomize

    - name: Deploy to GKE
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT }}
        GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
        GKE_ZONE: ${{ secrets.GKE_ZONE }}
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID
        kubectl apply -k ./k8s
