Skip to content
Navigation Menu
vutd22uit
/
pod-man

Type / to search

Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
Deploy to GKE
Update web-deployment.yml #6
Jobs
Run details
Workflow file for this run
.github/workflows/deploy.yml at 0854dc8
name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY_BASE64 }}
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Authenticate to Google Cloud Registry
      env:
        GCP_SA_KEY_BASE64: ${{ secrets.GCP_SA_KEY_BASE64 }}
      run: |
        echo "${GCP_SA_KEY_BASE64}" | base64 --decode > "${HOME}/gcp-key.json"
        gcloud auth activate-service-account --key-file="${HOME}/gcp-key.json"
        gcloud auth configure-docker gcr.io
    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/my-knowledge-site-web:latest ./web
    - name: Push Docker image to GCR
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT }}/my-knowledge-site-web:latest
    - name: Install gke-gcloud-auth-plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin
    - name: Deploy to GKE
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT }}
        GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
        GKE_ZONE: ${{ secrets.GKE_ZONE }}
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID
        kubectl apply -k ./k8s
        
